### ISSUE TITLE
[Referal Contest] Do you have dreams?

### ISSUE THREAD

**Issue by cm-t** [MycroftAI/skill-personal#31]
Hi,

I won the referral contest for Mark I.

> Hey Arudy,
> 
> You got third place in the Mycroft referral contest! That's awesome!
> 
> As such you get a custom message in Mycroft's longterm memory! So be thinking about what you'd like the message to be and the query that triggers it! Try to keep it PG-rated at least please. > Let me know if you have any questions or need help!
> _Ryan Sipes_

I've communicated with Ryan at that time on telegram (…).

My surprise is now, after reinstalling mark I (and patiently waiting for mark-II), my sentence is still not in Mycroft's memory.
It is not a big deal, I'm not upset or anything, i understand people come and go and all, even me wasn't a lot active as I wanted on the project…

Let me know if this is the right sub-project to open this issue, or not ^^

Please contact me if you need a proof of identity (see my contact info at https://launchpad.net/~cm-t ) or me forwarding the original email, or whatever :)

** ** 

Here is my proposal: 

**Trigger:**
> _Hey Mycroft_, do you have dreams ?

Eventually optional trigger if you allow it _(I think the rules was about only 1 trigger)_
> _Hey Mycroft_, do you dream ?
> _Hey Mycroft_, do you have a dream ?

**Unique anwser** :
> The most important is what you, human being, dream of, and above all, you should always believe in your dream for it's a beautiful dream and without your dream there can be nothing.

** ** 

FR-fr : 
> Le plus important est ce que dont vous, être-humain, rêvez, et par-dessus tout, vous devriez toujours croire en votre rêve, car c’est un beau rêve et sans votre rêve, il ne peut y rien avoir.

** ** 
The story behind:

> I went in the _Little Scotland_ (Arran) during the summer at the time of the contest and during my treck, i've meet this guy who allowed us to visit his wonderful lands.
>
> He manage a land and he is building for years a path so people can visit/walk in his land until they meet rivers, the waterfall and a loch.
>With others volunteers, he makes a huge work to **allow everyone**, including disabled people, to be able to do that visit and to make sure the path is also **nature friendly**.
> On the welcome board of the lands, that sentence was there: **_'always beleive in your dream for it's a beautiful dream and without your dream there can be nothing'_**. 
> 
> We have more and more AI references in the pop/nowdays culture such as in movies, I've noticed they make us think about the doubt if it's alive or not by making the AI having dream or pretending they have dream.
> 
> That's it, I've used this to introduce the quote of the [Albert of Eas-Mor](http://easmor-ecology.com/begining.htm)'s mantra.

NB: I'm not a native english speaker, so if the beginning of the anwser doesn't feel natural to transitionate with the quote, please let me know, i am open to update the sentence.

Thank to all contributors o/

**Comment by penrods** [comment]
Hi @cm-t!  That contest was, unfortunately, poorly tracked and the winners got lost when Ryan left the project 4 years ago.  One other person contacted me a couple years ago and I implemented it and then I tried to track down the others but had no luck figuring out who they were.  I'd be happy to make sure your phrase gets implemented.

**Comment by forslund** [comment]
The phrase has been added and I've submitted the skill to the skills repo. Sorry for the delay in adding this. I'm closing this issue now, the devices will be updated with this as soon as the skill has been reviewed.

Thanks for your contribution to the Mycroft project!

**Comment by krisgesling** [comment]
Hey @cm-t just a quick note that this has been merged into the Marketplace, and it will update on devices automatically. Thanks for spreading good dreams to all our users!

**Comment by cm-t** [comment]
PS: I've tested it, works well, thank you everyone o/
